### ISSUE TITLE
pc-chat在我的mac上run不起来

### ISSUE THREAD

**Issue by robinli0118** [wildfirechat/pc-chat#1]
npm run dev后有如下log:
Macintosh:pc-chat lijibin$ npm run dev

> wildfireChat@0.1.7 dev /Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[1] 
[1] > wildfireChat@0.1.7 start-hot /Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat
[1] > cross-env HOT=1 NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill ./main
[1] 
[0] 
[0] > wildfireChat@0.1.7 hot-server /Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat
[0] > cross-env NODE_ENV=development node -r babel-register scripts/dev.js
[0] 
[1] 2019-05-13 09:45:05.733 Electron[23751:3893460] *** WARNING: Textured window <AtomNSWindow: 0x7fa8714e6d90> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[0] Server is running with port 3000 👏
[0] webpack built 805a5a5b6c2601e53a26 in 28731ms
[0] ✖ ｢wdm｣: Hash: 805a5a5b6c2601e53a26
[0] Version: webpack 4.31.0
[0] Time: 28731ms
[0] Built at: 2019/05/13 上午9:45:35
[0]                                       Asset     Size  Chunks  Chunk Names
[0]                                   bundle.js   15 MiB    main  main
[0]  src/assets/fonts/icomoon/fonts/icomoon.eot  146 KiB          
[0]  src/assets/fonts/icomoon/fonts/icomoon.svg  311 KiB          
[0]  src/assets/fonts/icomoon/fonts/icomoon.ttf  146 KiB          
[0] src/assets/fonts/icomoon/fonts/icomoon.woff  146 KiB          
[0] Entrypoint main = bundle.js
[0] [0] multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr babel-polyfill ./src/app.js 52 bytes {main} [built]
[0] [./node_modules/babel-polyfill/lib/index.js] 833 bytes {main} [built]
[0] [./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js] 23.9 KiB {main} [built]
[0] [./node_modules/core-js/fn/regexp/escape.js] 108 bytes {main} [built]
[0] [./node_modules/core-js/shim.js] 8.03 KiB {main} [built]
[0] [./node_modules/mobx-react/index.module.js] 48.4 KiB {main} [built]
[0] [./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[0] [./node_modules/react-router-dom/es/index.js] 1010 bytes {main} [built]
[0] [./node_modules/react-transform-catch-errors/lib/index.js] 2.62 KiB {main} [built]
[0] [./node_modules/react-transform-hmr/lib/index.js] 3.6 KiB {main} [built]
[0] [./node_modules/react/index.js] 190 bytes {main} [built]
[0] [./node_modules/redbox-react/lib/index.js] 16 KiB {main} [built]
[0] [./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[0] [./node_modules/webpack-hot-middleware/client.js?path=http://localhost:3000/__webpack_hmr] (webpack)-hot-middleware/client.js?path=http://localhost:3000/__webpack_hmr 7.68 KiB {main} [built]
[0] [./src/app.js] 11.2 KiB {main} [built]
[0]     + 958 hidden modules
[0] 
[0] WARNING in ./node_modules/write-file-atomic/index.js
[0] Module not found: Error: Can't resolve 'worker_threads' in '/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/write-file-atomic'
[0]  @ ./node_modules/write-file-atomic/index.js
[0]  @ ./node_modules/electron-json-storage/lib/storage.js
[0]  @ ./src/js/utils/storage.js
[0]  @ ./src/js/stores/sessions.js
[0]  @ ./src/js/stores/index.js
[0]  @ ./src/app.js
[0]  @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr babel-polyfill ./src/app.js
[0] 
[0] ERROR in ./node_modules/tributejs/dist/tribute.js
[0] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[0] Error: Couldn't find preset "env" relative to directory "/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/tributejs"
[0]     at /Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
[0]     at Array.map (<anonymous>)
[0]     at OptionManager.resolvePresets (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
[0]     at OptionManager.mergePresets (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
[0]     at OptionManager.mergeOptions (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
[0]     at OptionManager.init (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
[0]     at File.initOptions (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/file/index.js:212:65)
[0]     at new File (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/file/index.js:135:24)
[0]     at Pipeline.transform (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
[0]     at transpile (/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/node_modules/babel-loader/lib/index.js:50:20)
[0]  @ ./src/js/components/MessageInput/index.js 55:17-37
[0]  @ ./src/js/pages/BatchSend/index.js
[0]  @ ./src/js/pages/Layout.js
[0]  @ ./src/js/pages/index.js
[0]  @ ./src/js/routes.js
[0]  @ ./src/app.js
[0]  @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr babel-polyfill ./src/app.js
[0] 
[0] ERROR in ./src/js/wfc/wfc.js
[0] Module not found: Error: Can't resolve 'node-loader' in '/Users/lijibin/Work/Tigase/wildfirechat_pc/pc-chat/src/js/wfc'
[0]  @ ./src/js/wfc/wfc.js 17:19-80
[0]  @ ./src/js/stores/sessions.js
[0]  @ ./src/js/stores/index.js
[0]  @ ./src/app.js
[0]  @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr babel-polyfill ./src/app.js
[0] ℹ ｢wdm｣: Failed to compile.

我开始以为是我环境的问题，卸载了我的npm环境，重装了最新版，重新下载和install 也不行

**Comment by heavyrain2012** [comment]
目前pc还在开发中，预计一个月后，请耐心等待

**Comment by imndx** [comment]
你哈，可以再试试了
